vars:
  mod: 'Mod1'
  font-0-size: '10'

display:
  primary: eDP1
  layout: xrandr --output eDP1 --auto

polybar:
  height: 25
  networks:
  - enp0s13f0u2u4u4
  - wlp9s0
  options:
  - battery
  - microphone

i3:
  options:
  - gaps

  bindings:
    "Print": "exec --no-startup-id $HOME/.config/i3/scripts/screenshot.sh"
    "XF86AudioRaiseVolume": "exec --no-startup-id pactl get-default-sink | xargs -I{} pactl set-sink-volume {} +5%"
    "XF86AudioLowerVolume": "exec --no-startup-id pactl get-default-sink | xargs -I{} pactl set-sink-volume {} -5%"
    "$mod+XF86MonBrightnessUp": "exec --no-startup-id light -s sysfs/leds/tpacpi::kbd_backlight -r -A 1"
    "$mod+XF86MonBrightnessDown": "exec --no-startup-id light -s sysfs/leds/tpacpi::kbd_backlight -r -U 1"
    "XF86AudioMute": "exec --no-startup-id pactl get-default-sink | xargs -I{} pactl set-sink-mute {} toggle"
    "XF86AudioMicMute": "exec --no-startup-id pactl get-default-source | xargs -I{} pactl set-source-mute {} toggle"
    "XF86MonBrightnessUp": "exec --no-startup-id light -s sysfs/backlight/auto -A 5"
    "XF86MonBrightnessDown": "exec --no-startup-id light -s sysfs/backlight/auto -U 5"
    "XF86Favorites": "exec $HOME/.favorite.sh"
    "$mod+p": 'exec --no-startup-id "rofi -combi-modi window,drun,calc -dpi 192 -theme rofi -show combi -display-window \\"\\" -display-drun \\"\\" -display-calc \\"\\" -display-combi \\">> \\""'

startup:
  - setxkbmap -option caps:swapescape
